---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: service-binding-7
spec:
  services:
  - group: "example.com"
    version: v1alpha1
    kind: BillService
    name: bill-service-1
  application:
    name: application-1
    group: apps
    version: v1
    resource: deployments
