---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: service-binding-3
spec:
  services:
  - group: ""
    version: v1
    kind: Secret
    name: secret-1
  application:
    name: application-1
    group: apps
    version: v1
    resource: deployments
